name: clojure-quest-build
on:
  push:
    branches:
      - main
jobs:
  clojure-quest-build:
    name: Build the site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.943'
          
      - name: maven cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run clj build
        run: make build-action

      - name: Deploy subtree
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: '_site'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
